apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: ayoubkoutari/task-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
