apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: Dev-container
        image: ayoubkoutari/Dev-devops:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
