apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: NodePort
  selector:
    app: task
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000  # Port accessible via IP_VM:31000
